# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

# Set the number of master and worker nodes
num_masters = 1
num_workers = 2

Vagrant.configure(2) do |config|
  config.vm.provision "shell", path: "bootstrap.sh"

  # Define machines dynamically
  (1..num_masters).each do |i|
    config.vm.define "master#{i}" do |master|
      master.vm.box = "generic/rhel8"
      master.vm.network "private_network", ip: "172.16.16.#{10 + i}"
      master.vm.hostname = "master#{i}.example.com"

      master.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"  # 2 GB RAM
        vb.cpus = 2         # 2 CPUs
      end
    end
  end

  (1..num_workers).each do |i|
    config.vm.define "worker#{i}" do |worker|
      worker.vm.box = "generic/rhel8"
      worker.vm.network "private_network", ip: "172.16.16.#{20 + num_masters + i}"
      worker.vm.hostname = "worker#{i}.example.com"

      worker.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"  # 2 GB RAM
        vb.cpus = 2         # 2 CPUs
      end
    end
  end
end
